services:
  orchestrator-slopmaker:
    container_name: orchestrator-slopmaker
    build: .
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - internal

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    networks:
      - internal
    volumes:
      - ollama-data:/root/.ollama
    tty: true
    environment:
      MODEL: ${MODEL-smollm2}
    healthcheck:
      test: ollama show $${MODEL}
      interval: 60s
      start_period: 5s

networks:
  internal:
    driver: bridge

volumes:
  ollama-data:
    driver: local
